apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-volume-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 40Gi



